# Generated by Django 5.1.5 on 2025-01-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cashflowrecord_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcategory',
            name='name',
            field=models.CharField(max_length=124, unique=True),
        ),
        migrations.AlterField(
            model_name='recordstatus',
            name='value',
            field=models.CharField(max_length=124, unique=True),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='value',
            field=models.CharField(max_length=124, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='recordsubcategory',
            unique_together={('name', 'category')},
        ),
    ]
