# Generated by Django 5.1.5 on 2025-01-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_recordcategory_name_alter_recordstatus_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowrecord',
            name='comment',
            field=models.CharField(max_length=124, null=True),
        ),
    ]
