# Generated by Django 5.1.5 on 2025-01-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cashflowrecord_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowrecord',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.recordcategory'),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='record_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.recordstatus'),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.recordtype'),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.recordsubcategory'),
        ),
    ]
